---
title: "SeattleBikeTraffic"
author: "Dash Wieland"
date: "4/1/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

This
```{r}
suppressPackageStartupMessages(library(dplyr))
library(lubridate)
library(ggplot2)
library(RColorBrewer)
```

```{r cars}
bike_traffic <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-04-02/bike_traffic.csv", col_types = 'cccdd') 
```

```{r}
bike_traffic$lubri_date = mdy_hms(bike_traffic$date)
```

```{r}
bike_taffic_dated <- bike_traffic %>%
  mutate(floor_month_year = month(lubri_date, label = TRUE),
         floor_week_year = week(lubri_date),
         floor_day_year = yday(lubri_date), 
         log_bike_count = log(bike_count))
```

```{r}
bike_taffic_grouped <- bike_taffic_dated %>%
  group_by(floor_week_year, crossing) %>%
  summarise(mean_bike_count = mean(bike_count, na.rm = TRUE))
```

```{r}
ggplot(bike_taffic_grouped, aes(x = floor_week_year, y = mean_bike_count)) + 
  geom_line(aes(color = crossing, group = crossing), size = 1) +
  geom_point(aes(color = crossing)) + 
  scale_color_brewer(palette="Set3") +
  coord_polar() + 
  theme(plot.subtitle = element_text(family = "Lato", 
                                     colour = "oldlace",
                                     size = 12,
                                     vjust = -3),
    plot.caption = element_text(family = "Lato", 
                                size = 8, 
                                colour = "oldlace",
                                hjust = 1.55), 
    axis.ticks = element_line(colour = "aliceblue", 
                              size = 1,
                              linetype = "dashed"),
    panel.grid.major = element_line(colour = "darkolivegreen3", 
                                    size = 0.4,
                                    linetype = "dotted"), 
    panel.grid.minor = element_line(linetype = "blank"), 
    axis.title = element_text(family = "Lato", 
                              face = "bold",
                              size = 12,
                              colour = "oldlace"), 
    axis.text = element_text(family = "Lato Medium",
                             size = 12, 
                             face = "bold", 
                             colour = "oldlace",
                             hjust = 1, 
                             vjust = 0.75), 
    axis.text.x = element_text(family = "Lato Medium", 
                               colour = "oldlace"), 
    axis.text.y = element_text(family = "Lato Medium"), 
    plot.title = element_text(family = "Lato",
                              size = 20,
                              face = "bold",
                              colour = "oldlace", 
                              hjust = -.01, 
                              vjust = -2), 
    legend.text = element_text(family = "Lato", 
                               colour = "oldlace"), 
    legend.title = element_text(face = "bold",
                                family = "Lato",
                                colour = "oldlace"), 
    panel.background = element_rect(fill = "darkseagreen4"), 
    plot.background = element_rect(fill = "darkseagreen4"),
    legend.key = element_blank(),
    legend.background = element_rect(fill = "darkseagreen4")) +
  labs(title = "Weekly Average Bike Traffic in Seattle", 
       x = "Week of Year",
       y = "Average Bike Count", 
       colour = "Crossing", 
       subtitle = "The average number of bikes passing each counting station, aggregated by week of the year",
       caption = "Made by @DashWieland for #TidyTuesday") + 
  geom_vline(xintercept=1, colour="oldlace") +
  geom_text(aes(x=1,
                label="January",
                y=20),
            colour="oldlace",
            angle=90,
            hjust = -2.2,
            vjust = -.5) + 
  geom_vline(xintercept=18, colour="oldlace") +
  geom_text(aes(x=18,
                label="Late April/Early May)",
                y=20),
            colour="oldlace",
            angle=-27,
            hjust = -0.82,
            vjust = -.3) +   
  geom_vline(xintercept=34, colour="oldlace") + 
  geom_text(aes(x=34,
                label="Late August",
                y=20), 
            colour="oldlace",
            angle= 43,
            hjust = 2.5,
            vjust = -.75)
```

```{r}
p + geom_vline(xintercept=1, colour="oldlace") +
  geom_text(aes(x=1,
                label="\nJanuary",
                y=20),
            colour="oldlace",
            angle=90,
            hjust = -1.55,
            vjust = .2) + 
  geom_vline(xintercept=18, colour="oldlace") +
  geom_text(aes(x=18,
                label="Late April/Early May)",
                y=20),
            colour="oldlace",
            angle=-27,
            hjust = -0.6,
            vjust = .4) +   
  geom_vline(xintercept=34, colour="oldlace") + 
  geom_text(aes(x=34,
                label="Late August",
                y=20), 
            colour="oldlace",
            angle= 43,
            hjust = 2,
            vjust = .25)
```



